version: '3.8'

services:
  webserver:
    image: nginx:stable
    container_name: webserver
    ports:
      - "80:80"       # Pastikan port 80 tidak digunakan oleh layanan lain
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    restart: always

  fail2ban:
    image: crazymax/fail2ban
    container_name: fail2ban
    volumes:
      - ./logs:/var/log/nginx      # Log Nginx untuk dipantau
      - ./fail2ban:/data           # Konfigurasi Fail2Ban
    cap_add:
      - NET_ADMIN
    restart: always
